baseURL = "/"
languageCode = "en-us"
title = "Alec Benson"
theme = "cactus"
relativeURLs = true
canonifyURLs = true

paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  mainSection = "posts"
  mainSectionTitle = "Posts"
  colortheme = "white"